Repository WordPress/twentytwenty, pull requests merged in 2019-10, with the labels that each got.

#704 `<aside>` tag outside `<main>` tag
  404.php
  index.php
  singular.php
  templates/template-cover.php
Labels: needs testing

#626 Add stylelint `stylelint-a11y` plugin
  .stylelintrc.json
  package-lock.json
  package.json
  style-rtl.css
  style.css
Labels: accessibility, code quality

#707 Adds padding for paragraphs in full-width columns block
  style.css
Labels: needs decision

#758 Update CSS and RTL CSS style vendor prefixes per WPCS
  CONTRIBUTING.md
  assets/css/editor-style-classic-rtl.css
  assets/css/editor-style-classic.css
  package-lock.json
  package.json
  postcss.config.js
  style-rtl.css
  style.css
Labels: build tooling, code quality

#788 Remove Background image option
  classes/class-twentytwenty-customize.php
Labels: enhancement, needs decision

#778 Fix phpcs.xml.dist indentation, tabs, not spaces
  phpcs.xml.dist
Labels: code quality

#872 Improve color calculations
  assets/js/color-calculations.js
Labels: bug

#852 Update aria-expanded
  assets/js/index.js
  classes/class-twentytwenty-walker-page.php
  inc/template-tags.php
  template-parts/modal-menu.php
  template-parts/modal-search.php
Labels: accessibility

#865 Hide decorative HTML entities
  classes/class-twentytwenty-walker-comment.php
  comments.php
  footer.php
  template-parts/entry-author-bio.php
  template-parts/navigation.php
  template-parts/pagination.php
Labels: accessibility

#589 UPDATE #588: Update print styles
  print.css
Labels: WIP
