Repository WordPress/twentytwenty, pull requests merged in 2019-09, with the labels that each got.

#244 Sync Master and Develop
  CONTRIBUTORS.md
  content.php
  functions.php
  inc/custom-css.php
  inc/svg-icons.php
  inc/template-tags.php
  index.php
  singular.php
  template-parts/content-cover.php
  template-parts/content.php
  template-parts/featured-image.php
  template-parts/navigation.php
Labels: high priority

#233 UPDATE #119: Center search form
  index.php
Labels: needs design feedback

#249 Auto-calculate background-color luminance (#a11y)
  classes/class-twentytwenty-color.php
  functions.php
  inc/template-tags.php
Labels: accessibility

#247 Update Menu names
  footer.php
  functions.php
  header.php
  inc/template-tags.php
  style.css
  template-parts/modal-menu.php
Labels: menu

#339 Issue/29 2/async defer javascript
  CONTRIBUTORS.md
  classes/class-twentytwenty-script-loader.php
  functions.php
Labels: enhancement

#163 Move from jQuery to using Vanilla JS (ES5)
  assets/js/construct.js
  assets/js/index.js
  functions.php
  style.css
Labels: enhancement, high priority, needs testing

#377 Update `style.css` per WordPress Coding Standards
  style-rtl.css
  style.css
Labels: code quality

#386 Update `assets/css/font-awesome.css` per WordPress Coding Standards
  assets/css/font-awesome.css
Labels: code quality

#385 Update `assets/js/index.js` per WordPress Coding Standards
  assets/js/index.js
Labels: code quality

#387 Update `assets/css/editor-style-classic.css` per WordPress Coding Standards
  assets/css/editor-style-classic.css
Labels: code quality

#388 Update `assets/css/editor-style-block.css` per WordPress Coding Standards
  assets/css/editor-style-block.css
Labels: code quality

#375 Update Composer files per WordPress Coding Standards
  composer.json
  composer.lock
Labels: build tooling, code quality

#374 Update `.editorconfig` to latest WordPress version
  .editorconfig
Labels: build tooling, code quality

#363 add @wordpress/scripts package
  .eslintrc
  .stylelintrc.json
  .travis.yml
  package-lock.json
  package.json
Labels: build tooling

#351 See #284
  assets/js/color-calculations.js
  assets/js/customize-controls.js
  assets/js/customize-preview.js
  classes/class-twentytwenty-color.php
  classes/class-twentytwenty-customize.php
  functions.php
  inc/custom-css.php
  inc/template-tags.php
Labels: WIP

#491 Update `package.json` & `package-lock.json` per WordPress Coding Standards
  package-lock.json
  package.json
Labels: code quality

#528 Update `package.json` format per WordPress Coding Standards
  .travis.yml
  package.json
Labels: build tooling, code quality

#561 Add `:focus` pseudo-class selector to `:hover` selectors
  assets/css/editor-style-classic.css
  functions.php
  style.css
Labels: accessibility

#361 Changed cursor for close state in modals
  style.css
Labels: needs decision

#619 Update licensing information
  README.md
  readme.txt
Labels: WIP
