Repository WordPress/twentytwenty, pull requests merged in 2019-11, with the labels that each got.

#949 touch devices: open submenus on the desktop horizontal menu
  assets/js/index.js
Labels: help wanted, menu

#820 loop index.js
  assets/js/index.js
Labels: Future Consideration

#701 Refactor responsive behavior to better deal with nested .alignwide and .alignfull blocks.
  assets/css/editor-style-block.css
  style.css
  template-parts/content.php
Labels: WIP
